package com.iona.laboraAI.chemistry.core.valueObjects;

import lombok.Value;

@Value
public class TitrationResult {
    Double concentration;             // Calculated molarity of analyte
    String unit;                      // e.g., "M" (Molarity)
    Double averageTitre;              // Volume of titrant used (endReading - startReading)
    Double standardDeviation;         // Accuracy measurement over trials
    Boolean phAvailable;              // Whether pH curve readings were submitted
    String equivalencePointInsight;   // Detailed qualitative review generated by AI
}